#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libvirt-python
Version  : 5.8.0
Release  : 61
URL      : https://github.com/libvirt/libvirt-python/archive/v5.8.0.tar.gz
Source0  : https://github.com/libvirt/libvirt-python/archive/v5.8.0.tar.gz
Summary  : libvirt python binding
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: libvirt-python-license = %{version}-%{release}
Requires: libvirt-python-python = %{version}-%{release}
Requires: libvirt-python-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : libvirt-dev
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : util-linux
BuildRequires : virtualenv

%description
Some simple examples on how to use the Python API for libvirt
The examples are:
dominfo.py  - print information about a running domU based on the results of
virDomainGetInfo and virDomainGetXMLDesc
domstart.py - create a domU from an XML description if the domU isn't
running yet
domsave.py  - save all running domU's into a directory
domrestore.py - restore domU's from their saved files in a directory
esxlist.py  - list active domains of an VMware ESX host and print some info.
also demonstrates how to use the libvirt.openAuth() method
dhcpleases.py - list dhcp leases for a given virtual network
domipaddrs.py - list IP addresses for guest domains
guest-vcpus - two helpers to make the guest agent event useful with agent based
vCPU state modification
nodestats.py - print total memory and free memory for each host NUMA node and
the memory strictly bound to certain host nodes for each running
domain.

%package license
Summary: license components for the libvirt-python package.
Group: Default

%description license
license components for the libvirt-python package.


%package python
Summary: python components for the libvirt-python package.
Group: Default
Requires: libvirt-python-python3 = %{version}-%{release}

%description python
python components for the libvirt-python package.


%package python3
Summary: python3 components for the libvirt-python package.
Group: Default
Requires: python3-core
Provides: pypi(libvirt-python)

%description python3
python3 components for the libvirt-python package.


%prep
%setup -q -n libvirt-python-5.8.0
cd %{_builddir}/libvirt-python-5.8.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583169887
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libvirt-python
cp %{_builddir}/libvirt-python-5.8.0/COPYING %{buildroot}/usr/share/package-licenses/libvirt-python/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/libvirt-python-5.8.0/COPYING.LESSER %{buildroot}/usr/share/package-licenses/libvirt-python/01a6b4bf79aca9b556822601186afab86e8c4fbf
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libvirt-python/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/libvirt-python/4cc77b90af91e615a64ae04893fdffa7939db84c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
